import Head from "next/head";
import Image from "next/image";

import homeStyles from "@/styles/Home.module.css";

import {Navbar, Nav, NavDropdown, Button} from "react-bootstrap";
import Card from "react-bootstrap/Card";
import Col from "react-bootstrap/Col";
import Row from "react-bootstrap/Row";

export default function Home() {
 const imageUrls = [
  "/images/services.webp",
  "/images/job.jpg",
  "/images/service.png",
  "/images/staff.jpg",
 ];

 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <Navbar bg="light" expand="lg" className="justify-content-between">
    <Navbar.Brand href="#home" className="ms-4">
     My Website
    </Navbar.Brand>
    <Navbar.Toggle aria-controls="basic-navbar-nav" />
    <Navbar.Collapse id="basic-navbar-nav">
     <Nav className="ms-auto me-4">
      <Nav.Link href="#home">Home</Nav.Link>
      <Nav.Link href="#about">About</Nav.Link>
      <Nav.Link href="#contact">Contact</Nav.Link>
     </Nav>
    </Navbar.Collapse>
   </Navbar>

   <section className={homeStyles.cards + " ms-*"}>
    <Row xs={1} md={2} className="g-4">
     {Array.from({length: 4}).map((_, idx) => (
      <Col key={idx}>
       <Card>
        <div style={{position: "relative", width: "100%", height: "200px"}}>
         <Image src={imageUrls[idx]} alt="Service image" fill />
        </div>
        <Card.Body>
         <Card.Title>Card title</Card.Title>
         <Card.Text>
          This is a longer card with supporting text below as a natural lead-in
          to additional content. This content is a little bit longer.
         </Card.Text>
         <Button variant="primary">Go somewhere</Button>
        </Card.Body>
       </Card>
      </Col>
     ))}
    </Row>
   </section>
  </>
 );
}
